### ISSUE TITLE
Think of less stupid name for project

### ISSUE THREAD

**Issue by jradavenport** [StellarArmy/tricycle#3]
The name "perth" is stupid. Can we think of something better?

e.g. "3PO" or "tricycle"?

**Comment by kweis** [comment]
Ooooooooh. Tricycle is amazing.

On May 13, 2015, at 3:47 PM, James Davenport notifications@github.com
wrote:

The name "perth" is stupid. Can we think of something better?

e.g. "3PO" or "tricycle"?

—
Reply to this email directly or view it on GitHub
https://github.com/StellarArmy/perth/issues/3.

**Comment by adleorocks** [comment]
Haha, I like tricycle also!

On May 13, 2015, at 3:49 PM, kolbylyn notifications@github.com wrote:

Ooooooooh. Tricycle is amazing.

On May 13, 2015, at 3:47 PM, James Davenport notifications@github.com
wrote:

The name "perth" is stupid. Can we think of something better?

e.g. "3PO" or "tricycle"?

—
Reply to this email directly or view it on GitHub
https://github.com/StellarArmy/perth/issues/3.
